### ISSUE TITLE
[Feature] Audit logging, tracking and endpoints

### ISSUE THREAD

**Issue by DeadlyFirex** [DeadlyFirex/PrimoTracker#4]
**Description**
Automatize the `audit_log` table implemented in prior versions,
This will allow the project to "journal" actions of users and administrators.
Furthermore, add endpoints to leverage this table to administrators.

**Context**
As of right now, prior versions have implemented the tables, but lack integration with the audit and transaction tables. 
This feature specifically focuses on the `audit_log`.

**Expected Behavior**
- Design functions and methods to automatize user tracking.
- Automatize the `audit_log` table in conjunction with all other (unrelated) endpoints.
- Create endpoints to interact with this data, for users, and the administrators.

**Use Case Examples**
- Administrators should be able to view actions performed by the system and by users / admins in the audit log.
- Users and administrators should be able to view and interact with this data, depending on the context.

**Requirements**
- [ ] Research implementation
- [ ] Optionally extend on configuration 
- [ ] Create functions, methods or decorators for unrelated endpoints
- [ ] Design and implement endpoints to interact with audit log
- [ ] Testing and verification
- [ ] Integration into deployment

**Considerations**
- Optional: create extended configuration fields to manage this function
- Optional: create decorators to manage this behavior

**Additional Information**
N/A

**Dependencies**
- Depends-on: #7  

**Related**
- Related-to: #5 
- Related-to: #7
